# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kkostya/fun/hax/lllllllatest/linux-csgo-external

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kkostya/fun/hax/lllllllatest/linux-csgo-external

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kkostya/fun/hax/lllllllatest/linux-csgo-external/CMakeFiles /home/kkostya/fun/hax/lllllllatest/linux-csgo-external/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kkostya/fun/hax/lllllllatest/linux-csgo-external/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named csgo_external

# Build rule for target.
csgo_external: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csgo_external
.PHONY : csgo_external

# fast build rule for target.
csgo_external/fast:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/build
.PHONY : csgo_external/fast

hack.o: hack.cpp.o
.PHONY : hack.o

# target to build an object file
hack.cpp.o:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/hack.cpp.o
.PHONY : hack.cpp.o

hack.i: hack.cpp.i
.PHONY : hack.i

# target to preprocess a source file
hack.cpp.i:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/hack.cpp.i
.PHONY : hack.cpp.i

hack.s: hack.cpp.s
.PHONY : hack.s

# target to generate assembly for a file
hack.cpp.s:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/hack.cpp.s
.PHONY : hack.cpp.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/main.cpp.s
.PHONY : main.cpp.s

remote.o: remote.cpp.o
.PHONY : remote.o

# target to build an object file
remote.cpp.o:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/remote.cpp.o
.PHONY : remote.cpp.o

remote.i: remote.cpp.i
.PHONY : remote.i

# target to preprocess a source file
remote.cpp.i:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/remote.cpp.i
.PHONY : remote.cpp.i

remote.s: remote.cpp.s
.PHONY : remote.s

# target to generate assembly for a file
remote.cpp.s:
	$(MAKE) -f CMakeFiles/csgo_external.dir/build.make CMakeFiles/csgo_external.dir/remote.cpp.s
.PHONY : remote.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... csgo_external"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hack.o"
	@echo "... hack.i"
	@echo "... hack.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... remote.o"
	@echo "... remote.i"
	@echo "... remote.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

